version: '2.2'
services:
  app-postgres:
    image: "postgres"
    container_name: app-postgres
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=app
    ports:
      - 5432:5432
    volumes:
      - data-postgres:/var/lib/postgresql/data
      - ./hello_world.sql:/docker-entrypoint-initdb.d/1-hello_world.sql
    networks:
      - postgres
  app:
    build: .
    container_name: app
    environment:
      - DB_USERNAME=test
      - DB_PASSWORD=test
      - DB_NAME=app
      - DB_SERVER=app-postgres
    ports:
      - 5000:5000
    depends_on:
      - app-postgres
    networks:
      - postgres
volumes:
  data-postgres:
    driver: local
networks:
  postgres:
    driver: bridge